import { writeFileSync } from 'fs';
import { dedent } from 'tslint/lib/utils';

const util = require('util');
const exec = util.promisify(require('child_process').exec);
function editTime(_time: number) {
  return _time.toString().length === 1 ? '0' + _time : _time;
}
async function createVersionsFile(filename: string) {
  const revision = (await exec('git rev-parse --short HEAD')).stdout.toString().trim();
  const branch = (await exec('git rev-parse --abbrev-ref HEAD')).stdout.toString().trim();
  const str = (await exec('git tag -n9 | tail -1')).stdout.toString().trim();
  const tag = str.substr(0, str.indexOf(' ')); // "72"
  const comment = str.substr(str.indexOf(' ') + 1).trim();
  const date = new Date();
  const build =  editTime(date.getDate()) +
    '/' + editTime((date.getMonth() + 1)) +
    '/' + date.getFullYear() +
    ' ' + editTime(date.getHours()) +
    ':' + editTime(date.getMinutes());

  const content = dedent`
      // this file is automatically generated by git.version.ts script
      export const versions = {
        build: '${build}',
        comment: '${comment}',
        version: '${tag}',
        revision: '${revision}',
        branch: '${branch}',
      };
      `;

  writeFileSync(filename, content, { encoding: 'utf8' });
}

createVersionsFile('src/environments/versions.ts');
