/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Model } from './model';
import { Segment } from './segment';


export interface PartDTO {
    charging?: string;
    exclusive?: boolean;
    id?: number;
    idCompany?: number;
    model?: Model;
    name?: string;
    picture?: string;
    provider?: string;
    segment?: Segment;
    serialNumber?: string;
}
