/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from './character';
import { City } from './city';
import { Establishment } from './establishment';
import { User } from './user';


export interface Address {
    addrDefault?: Character;
    city?: City;
    createdAt?: Date;
    establishment?: Establishment;
    id?: number;
    latitude?: number;
    longitude?: number;
    neighborhood?: string;
    number?: string;
    street?: string;
    updatedAt?: Date;
    user?: User;
    zip?: string;
}
