/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PartResponseDTO {
    charging?: string;
    exclusive?: boolean;
    id?: number;
    idCompany?: number;
    idFabricator?: number;
    idModel?: number;
    idSegment?: number;
    name?: string;
    nameFabricator?: string;
    nameModel?: string;
    picture?: string;
    provider?: string;
    serialNumber?: string;
}
