/**
 * ws-performa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.7-20190109095830
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompanyDTO } from './companyDTO';
import { DefectDTO } from './defectDTO';
import { DepartmentDTO } from './departmentDTO';
import { DowntimeHeaderDTO } from './downtimeHeaderDTO';
import { DowntimeReasonDTO } from './downtimeReasonDTO';
import { EmployeeDTO } from './employeeDTO';
import { LineDTO } from './lineDTO';
import { MachineDTO } from './machineDTO';
import { WorkstationDTO } from './workstationDTO';


export interface DowntimeDetailDTO {
    company?: CompanyDTO;
    dateClerk?: Date;
    dateClose?: Date;
    dateOpen?: Date;
    defect?: DefectDTO;
    defectClerk?: DefectDTO;
    department?: DepartmentDTO;
    downtimeHeader?: DowntimeHeaderDTO;
    downtimeReason?: DowntimeReasonDTO;
    downtimeReasonClerk?: DowntimeReasonDTO;
    employeeClerk?: EmployeeDTO;
    employeeClose?: EmployeeDTO;
    employeeOpen?: EmployeeDTO;
    id?: number;
    line?: LineDTO;
    machine?: MachineDTO;
    observationClose?: string;
    observationOpen?: string;
    status?: number;
    workstation?: WorkstationDTO;
}
