/**
 * ws-performa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.7-20190109095830
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompanyDTO } from './companyDTO';
import { ModelDTO } from './modelDTO';
import { RouteWorkstationDTO } from './routeWorkstationDTO';


export interface RouteDTO {
    active?: boolean;
    company?: CompanyDTO;
    idRoute?: number;
    model?: ModelDTO;
    nameRoute?: string;
    routeWorkstations?: Array<RouteWorkstationDTO>;
    totalTime?: number;
}
