/**
 * ws-performa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.7-20190109095830
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BomDTO } from './bomDTO';
import { CompanyDTO } from './companyDTO';
import { RouteDTO } from './routeDTO';
import { WorkstationDTO } from './workstationDTO';


export interface RouteWorkstationDTO {
    bom?: BomDTO;
    bypass?: boolean;
    company?: CompanyDTO;
    idRouteWorkstation?: number;
    route?: RouteDTO;
    seq?: number;
    sideBoard?: number;
    timeConveyor?: number;
    timeWork?: number;
    workstation?: WorkstationDTO;
}
