export * from './areasController.service';
import { AreasControllerService } from './areasController.service';
export * from './companyController.service';
import { CompanyControllerService } from './companyController.service';
export * from './databasesController.service';
import { DatabasesControllerService } from './databasesController.service';
export * from './defectClassController.service';
import { DefectClassControllerService } from './defectClassController.service';
export * from './defectsController.service';
import { DefectsControllerService } from './defectsController.service';
export * from './departmentsController.service';
import { DepartmentsControllerService } from './departmentsController.service';
export * from './downtimeDetailController.service';
import { DowntimeDetailControllerService } from './downtimeDetailController.service';
export * from './downtimeHeaderController.service';
import { DowntimeHeaderControllerService } from './downtimeHeaderController.service';
export * from './downtimeReasonController.service';
import { DowntimeReasonControllerService } from './downtimeReasonController.service';
export * from './downtimeTypeReasonController.service';
import { DowntimeTypeReasonControllerService } from './downtimeTypeReasonController.service';
export * from './employeesController.service';
import { EmployeesControllerService } from './employeesController.service';
export * from './linesController.service';
import { LinesControllerService } from './linesController.service';
export * from './machinesController.service';
import { MachinesControllerService } from './machinesController.service';
export * from './maintenanceActionController.service';
import { MaintenanceActionControllerService } from './maintenanceActionController.service';
export * from './modelsController.service';
import { ModelsControllerService } from './modelsController.service';
export * from './modulesController.service';
import { ModulesControllerService } from './modulesController.service';
export * from './movementHeadersController.service';
import { MovementHeadersControllerService } from './movementHeadersController.service';
export * from './movementHistoriesController.service';
import { MovementHistoriesControllerService } from './movementHistoriesController.service';
export * from './positionController.service';
import { PositionControllerService } from './positionController.service';
export * from './productionOrdersController.service';
import { ProductionOrdersControllerService } from './productionOrdersController.service';
export * from './profilesController.service';
import { ProfilesControllerService } from './profilesController.service';
export * from './routesController.service';
import { RoutesControllerService } from './routesController.service';
export * from './sessionsController.service';
import { SessionsControllerService } from './sessionsController.service';
export * from './shiftsController.service';
import { ShiftsControllerService } from './shiftsController.service';
export * from './technicalActionsController.service';
import { TechnicalActionsControllerService } from './technicalActionsController.service';
export * from './technicalAnalysisController.service';
import { TechnicalAnalysisControllerService } from './technicalAnalysisController.service';
export * from './workstationsController.service';
import { WorkstationsControllerService } from './workstationsController.service';
export const APIS = [AreasControllerService, CompanyControllerService, DatabasesControllerService, DefectClassControllerService, DefectsControllerService, DepartmentsControllerService, DowntimeDetailControllerService, DowntimeHeaderControllerService, DowntimeReasonControllerService, DowntimeTypeReasonControllerService, EmployeesControllerService, LinesControllerService, MachinesControllerService, MaintenanceActionControllerService, ModelsControllerService, ModulesControllerService, MovementHeadersControllerService, MovementHistoriesControllerService, PositionControllerService, ProductionOrdersControllerService, ProfilesControllerService, RoutesControllerService, SessionsControllerService, ShiftsControllerService, TechnicalActionsControllerService, TechnicalAnalysisControllerService, WorkstationsControllerService];
