/**
 * ws-performa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3.7-20190109095830
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { MovementHeaderDTO } from '../model/movementHeaderDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MovementHeadersControllerService {

    protected basePath = 'https://172.100.10.22:8082/ws-performa/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create new movement header
     * 
     * @param movementHeaderDTO movementHeader
     * @param idEmployee Employee Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createUsingPOST14(movementHeaderDTO: MovementHeaderDTO, idEmployee: number, observe?: 'body', reportProgress?: boolean): Observable<MovementHeaderDTO>;
    public createUsingPOST14(movementHeaderDTO: MovementHeaderDTO, idEmployee: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MovementHeaderDTO>>;
    public createUsingPOST14(movementHeaderDTO: MovementHeaderDTO, idEmployee: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MovementHeaderDTO>>;
    public createUsingPOST14(movementHeaderDTO: MovementHeaderDTO, idEmployee: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (movementHeaderDTO === null || movementHeaderDTO === undefined) {
            throw new Error('Required parameter movementHeaderDTO was null or undefined when calling createUsingPOST14.');
        }
        if (idEmployee === null || idEmployee === undefined) {
            throw new Error('Required parameter idEmployee was null or undefined when calling createUsingPOST14.');
        }

        let headers = this.defaultHeaders;
        if (idEmployee !== undefined && idEmployee !== null) {
            headers = headers.set('Id-Employee', String(idEmployee));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<MovementHeaderDTO>(`${this.basePath}/movement-headers`,
            movementHeaderDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find a running movement header by line
     * 
     * @param idLine idLine
     * @param idEmployee Employee Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findByRunningAndLineUsingGET(idLine: number, idEmployee: number, observe?: 'body', reportProgress?: boolean): Observable<MovementHeaderDTO>;
    public findByRunningAndLineUsingGET(idLine: number, idEmployee: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MovementHeaderDTO>>;
    public findByRunningAndLineUsingGET(idLine: number, idEmployee: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MovementHeaderDTO>>;
    public findByRunningAndLineUsingGET(idLine: number, idEmployee: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (idLine === null || idLine === undefined) {
            throw new Error('Required parameter idLine was null or undefined when calling findByRunningAndLineUsingGET.');
        }
        if (idEmployee === null || idEmployee === undefined) {
            throw new Error('Required parameter idEmployee was null or undefined when calling findByRunningAndLineUsingGET.');
        }

        let headers = this.defaultHeaders;
        if (idEmployee !== undefined && idEmployee !== null) {
            headers = headers.set('Id-Employee', String(idEmployee));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<MovementHeaderDTO>(`${this.basePath}/movement-headers/lines/${encodeURIComponent(String(idLine))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Movement Header by the Status
     * 
     * @param status status
     * @param idEmployee Employee Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findByUsingGET(status: number, idEmployee: number, observe?: 'body', reportProgress?: boolean): Observable<Array<MovementHeaderDTO>>;
    public findByUsingGET(status: number, idEmployee: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<MovementHeaderDTO>>>;
    public findByUsingGET(status: number, idEmployee: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<MovementHeaderDTO>>>;
    public findByUsingGET(status: number, idEmployee: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (status === null || status === undefined) {
            throw new Error('Required parameter status was null or undefined when calling findByUsingGET.');
        }
        if (idEmployee === null || idEmployee === undefined) {
            throw new Error('Required parameter idEmployee was null or undefined when calling findByUsingGET.');
        }

        let headers = this.defaultHeaders;
        if (idEmployee !== undefined && idEmployee !== null) {
            headers = headers.set('Id-Employee', String(idEmployee));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<MovementHeaderDTO>>(`${this.basePath}/movement-headers/status/${encodeURIComponent(String(status))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find movement header by production order
     * 
     * @param numProductionOrder numProductionOrder
     * @param idEmployee Employee Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getByProductionOrderUsingGET(numProductionOrder: string, idEmployee: number, observe?: 'body', reportProgress?: boolean): Observable<MovementHeaderDTO>;
    public getByProductionOrderUsingGET(numProductionOrder: string, idEmployee: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MovementHeaderDTO>>;
    public getByProductionOrderUsingGET(numProductionOrder: string, idEmployee: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MovementHeaderDTO>>;
    public getByProductionOrderUsingGET(numProductionOrder: string, idEmployee: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (numProductionOrder === null || numProductionOrder === undefined) {
            throw new Error('Required parameter numProductionOrder was null or undefined when calling getByProductionOrderUsingGET.');
        }
        if (idEmployee === null || idEmployee === undefined) {
            throw new Error('Required parameter idEmployee was null or undefined when calling getByProductionOrderUsingGET.');
        }

        let headers = this.defaultHeaders;
        if (idEmployee !== undefined && idEmployee !== null) {
            headers = headers.set('Id-Employee', String(idEmployee));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<MovementHeaderDTO>(`${this.basePath}/movement-headers/production-orders/${encodeURIComponent(String(numProductionOrder))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find movement header by its id
     * 
     * @param id id
     * @param idEmployee Employee Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUsingGET(id: number, idEmployee: number, observe?: 'body', reportProgress?: boolean): Observable<MovementHeaderDTO>;
    public getUsingGET(id: number, idEmployee: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MovementHeaderDTO>>;
    public getUsingGET(id: number, idEmployee: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MovementHeaderDTO>>;
    public getUsingGET(id: number, idEmployee: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getUsingGET.');
        }
        if (idEmployee === null || idEmployee === undefined) {
            throw new Error('Required parameter idEmployee was null or undefined when calling getUsingGET.');
        }

        let headers = this.defaultHeaders;
        if (idEmployee !== undefined && idEmployee !== null) {
            headers = headers.set('Id-Employee', String(idEmployee));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<MovementHeaderDTO>(`${this.basePath}/movement-headers/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update movement header
     * 
     * @param id id
     * @param movementHeaderDTO MovementHeader
     * @param idEmployee Employee Id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUsingPUT14(id: number, movementHeaderDTO: MovementHeaderDTO, idEmployee: number, observe?: 'body', reportProgress?: boolean): Observable<MovementHeaderDTO>;
    public updateUsingPUT14(id: number, movementHeaderDTO: MovementHeaderDTO, idEmployee: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MovementHeaderDTO>>;
    public updateUsingPUT14(id: number, movementHeaderDTO: MovementHeaderDTO, idEmployee: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MovementHeaderDTO>>;
    public updateUsingPUT14(id: number, movementHeaderDTO: MovementHeaderDTO, idEmployee: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateUsingPUT14.');
        }
        if (movementHeaderDTO === null || movementHeaderDTO === undefined) {
            throw new Error('Required parameter movementHeaderDTO was null or undefined when calling updateUsingPUT14.');
        }
        if (idEmployee === null || idEmployee === undefined) {
            throw new Error('Required parameter idEmployee was null or undefined when calling updateUsingPUT14.');
        }

        let headers = this.defaultHeaders;
        if (idEmployee !== undefined && idEmployee !== null) {
            headers = headers.set('Id-Employee', String(idEmployee));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<MovementHeaderDTO>(`${this.basePath}/movement-headers/${encodeURIComponent(String(id))}`,
            movementHeaderDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
