/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompanyDTO } from './companyDTO';
import { FabricatorDTO } from './fabricatorDTO';
import { ModeloDTO } from './modeloDTO';
import { SectorDTO } from './sectorDTO';
import { SegmentoDTO } from './segmentoDTO';


export interface MaterialDTO {
    address?: string;
    company?: CompanyDTO;
    fabricator?: FabricatorDTO;
    id?: number;
    maximunQuantity?: number;
    minimumQuantity?: number;
    model?: ModeloDTO;
    name?: string;
    realQuantity?: number;
    sector?: SectorDTO;
    segment?: SegmentoDTO;
    sinergiCode?: number;
    sinergiValue?: number;
}
