/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Company {
    cep?: string;
    cnpj?: string;
    complement?: string;
    contactName?: string;
    email?: string;
    fantasyName?: string;
    houseNumber?: string;
    id?: number;
    idBranch?: number;
    registrationMunicipal?: string;
    registrationState?: string;
    socialName?: string;
    street?: string;
    telephoneNumber?: string;
}
